# Generated by Django 4.1.4 on 2022-12-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Lead Source',
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Lead Stage',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line', models.CharField(blank=True, max_length=40, null=True)),
                ('address_state', models.CharField(blank=True, max_length=40, null=True)),
                ('address_city', models.CharField(blank=True, max_length=20, null=True)),
                ('post_code', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lead_source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource')),
                ('lead_stage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstage')),
            ],
        ),
    ]
