# Generated by Django 4.1.4 on 2022-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='leads/<django.db.models.fields.CharField>'),
        ),
    ]
