# Generated by Django 4.1.4 on 2022-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='leads'),
        ),
    ]
