# Generated by Django 4.1.4 on 2022-12-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('accounts', '0003_remove_account_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField()),
                ('close_type', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Deal Stage',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('expected_close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_close_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('deal_stage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.dealstage')),
            ],
            options={
                'verbose_name_plural': 'Deal',
            },
        ),
    ]
