# Generated by Django 4.1.4 on 2022-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_dealstage_close_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
