# Generated by Django 4.1.4 on 2022-12-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_upload_file'),
        ('deals', '0004_alter_deal_expected_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='accounts.account'),
        ),
    ]
