# Generated by Django 4.1.4 on 2022-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='deals'),
        ),
    ]
